#! /bin/sh

sxhkd &
picom &
/usr/lib/notification-daemon-1.0/notification-daemon &
# $HOME/.config/polybar/launch.sh &

bspc monitor HDMI-1 -n centre
bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap           4
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop="II" state=floating
bspc rule -a discord desktop="II" state=tiled
bspc rule -a jetbrains-studio desktop="III" state=floating

feh --bg-fill $HOME/Pictures/Wallpapers/The-Desert-5-dragged.jpg

xsetroot -cursor_name left_ptr &

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

tint2 &
nm-applet &
