#! /bin/sh

# Kill existing processes
pkill sxhkd
pkill picom
pkill polybar
pkill nm-applet
pkill dunst
pkill redshift
pkill xfce4-clipman

if [[ $(xrandr -q | grep "HDMI-1 connected") ]];
then
    ~/.screenlayout/HDMI_left_display.sh
    bspc wm -O eDP-1 HDMI-1
    bspc monitor eDP-1 -d 1 2 3 4 5
    bspc monitor HDMI-1 -d 6 7 8 9
else
    ~/.screenlayout/laptop_screen_only.sh
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
fi

# Start processes and applets
sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
nm-applet &
dunst &
redshift-gtk &
xfce4-clipman &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
thunar --daemon &

bspc config border_width         2
bspc config window_gap           2
bspc config top_padding          28
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config focus_follows_pointer true

bspc rule -a thunderbird desktop="1"
bspc rule -a firefox desktop="3"
bspc rule -a Brave-browser desktop="2"
bspc rule -a TelegramDesktop desktop="6" state=tiled
bspc rule -a Gimp-2.10 desktop="8" state=floating
bspc rule -a discord desktop="9"
bspc rule -a Zathura state=tiled

xsetroot -cursor_name left_ptr &

bspc config normal_border_color "#666666"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#47bf61"
bspc config presel_feedback_color "#47bf61"

feh --bg-fill $HOME/Pictures/wallpapers/current_wallpaper &
