#! /bin/sh

# Kill existing processes
pkill sxhkd
pkill picom
pkill polybar
pkill nm-applet
pkill dunst

# Start
sxhkd &
picom --experimental-backend &
$HOME/.config/polybar/launch.sh &
nm-applet &
dunst &

bspc monitor HDMI-1 -n centre
bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          0
bspc config bottom_padding       0  
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# bspc config focus_follows_pointer true

bspc rule -a firefox desktop="II"
bspc rule -a discord desktop="V"
bspc rule -a Gimp-2.10 desktop="VI" state=floating
bspc rule -a Zathura state=tiled 

xsetroot -cursor_name left_ptr &

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

feh --bg-fill $HOME/Pictures/wallpapers/current_wallpaper
